import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import confetti from 'canvas-confetti';

interface Temas {
  [key: string]: string[];
}

const temas: Temas = {
  'Mix': ['CASA', 'CARRO', 'MESA', 'LIVRO', 'ESCOLA', 'PORTA', 'JANELA', 'RUA', 'ÁRVORE', 'CAMA', 'QUARTO', 'COZINHA', 'BANHEIRO', 'SOFÁ', 'ESCRITÓRIO', 'TELEVISÃO', 'LÂMPADA', 'PRATO', 'TALHER', 'CADEIRA', 'GELADEIRA', 'FOGÃO', 'MICROONDAS', 'VENTILADOR', 'AR-CONDICIONADO', 'PISCINA', 'GARAGEM', 'JARDIM', 'TELHADO', 'CHÃO', 'PAREDE', 'TETO', 'ESCADA', 'CORREDOR', 'VARANDA', 'SALA', 'LAREIRA', 'QUINTAL', 'PORTÃO', 'CERCA', 'CHAVE', 'FECHADURA', 'INTERRUPTOR', 'TOMADA', 'LUSTRE', 'CORTINA', 'PERSIANA', 'ESPELHO', 'QUADRO', 'RELÓGIO', 'VASO', 'FLORES', 'PLANTA', 'ESTANTE', 'ARMÁRIO', 'GAVETA', 'COBERTOR', 'TRAVESSEIRO', 'LENÇOL', 'TOALHA', 'SABONETE', 'SHAMPOO', 'CONDICIONADOR', 'ESCOVA', 'PASTA', 'CREME', 'PENTE', 'SECADOR', 'CHUVEIRO', 'BANHEIRA', 'SANITÁRIO', 'PIA', 'TORNEIRA', 'ESGOTO', 'LIXEIRA', 'BALDE', 'VASSOURA', 'RODO', 'PANO', 'DETERGENTE', 'ABATJUR', 'TAPETE', 'MOLDURA', 'ALMOFADA', 'CESTO', 'FRUTEIRA', 'LIXEIRA', 'ESCORREDOR', 'FACA', 'GARFO', 'COLHER', 'XÍCARA', 'COPO', 'JARRA', 'PANELA', 'FRIGIDEIRA', 'ESPÁTULA', 'CONCHA', 'RALADOR', 'ABRIDOR', 'SACA-ROLHAS', 'DESCASCADOR', 'BATEDEIRA', 'LIQUIDIFICADOR', 'TORRADEIRA', 'CAFETEIRA', 'CHALEIRA', 'PANELA DE PRESSÃO', 'ESCUMADEIRA', 'PINÇA', 'TESOURA', 'PINCEL', 'ROLO', 'ESPONJA', 'ESCORREDOR', 'PENEIRA', 'FUNIL', 'MEDIDOR', 'BALANÇA', 'TERMÔMETRO', 'TIMER', 'DESCANSO', 'TRAVESSA', 'TIGELA', 'BOWL', 'PRATO DE SOBREMESA', 'PRATO FUNDO', 'PRATO RASO', 'SOPEIRA', 'MOLHEIRA', 'SALADEIRA', 'FRUTEIRA', 'QUEIJEIRA', 'MANTEIGUEIRA', 'AÇUCAREIRO', 'SALEIRO', 'PIMENTEIRO', 'PALITEIRO', 'GALHETEIRO', 'JOGO AMERICANO', 'TOALHA DE MESA', 'GUARDANAPO', 'PORTA-GUARDANAPO', 'PORTA-COPOS', 'PORTA-PRATOS', 'PORTA-TALHERES', 'PORTA-PÃO', 'PORTA-QUEIJO', 'PORTA-MANTEIGA', 'PORTA-AÇÚCAR'],
  'Animais': ['CACHORRO', 'ELEFANTE', 'GIRAFA', 'BORBOLETA', 'LEOPARDO', 'TIGRE', 'BALEIA', 'PINGUIM', 'JACARÉ', 'PAPAGAIO', 'GATO', 'CAVALO', 'COELHO', 'TARTARUGA', 'URSO', 'ONÇA', 'VEADO', 'RAPOSA', 'MACACO', 'MORCEGO', 'LEÃO', 'ZEBRA', 'HIPOPÓTAMO', 'RINOCERONTE', 'CANGURU', 'KOALA', 'PANDA', 'GORILA', 'CHIMPANZÉ', 'ORANGOTANGO', 'LOBO', 'RATO', 'RAPOSA', 'ESQUILO', 'CASTOR', 'GAMBA', 'TAMANDUÁ', 'PREGUIÇA', 'TATU', 'CAPIVARA', 'ANTA', 'JAVALI', 'PORCO', 'VACA', 'BOI', 'TOURO', 'CABRA', 'OVELHA', 'CARNEIRO', 'BURRO', 'MULA', 'JUMENTO', 'GALINHA', 'GALO', 'PATO', 'MARRECO', 'GANSO', 'PERU', 'CODORNA', 'AVESTRUZ', 'EMA', 'CISNE', 'FLAMINGO', 'PAVÃO', 'CORUJA', 'FALCÃO', 'ÁGUIA', 'CONDOR', 'URUBU', 'GAIVOTA', 'POMBO', 'ANDORINHA', 'CANÁRIO', 'PERIQUITO', 'CALOPSITA', 'ARARA', 'TUCANO', 'PICA-PAU', 'BEIJA-FLOR', 'PARDAL', 'ROUXINOL', 'SABIÁ', 'BEM-TE-VI', 'ABELHA', 'FORMIGA', 'BESOURO', 'BORBOLETA', 'GRILO', 'LAGARTA', 'LAGARTIXA', 'LAGARTO', 'COBRA', 'JARARACA', 'SUCURI', 'ANACONDA', 'ESCORPIÃO', 'ARANHA', 'CARANGUEJO', 'LAGOSTA', 'CAMARÃO', 'PEIXE', 'TUBARÃO', 'BALEIA', 'GOLFINHO', 'POLVO', 'LULA', 'ESTRELA-DO-MAR', 'CAVALO-MARINHO', 'MEDUSA', 'PINGUIM', 'FOCAS', 'LEÃO-MARINHO', 'MORSAS', 'TARTARUGA-MARINHA', 'PEIXE-BOI', 'LONTRA', 'CASTOR', 'RATO', 'RATAZANA', 'HAMSTER', 'PORQUINHO-DA-ÍNDIA', 'COELHO', 'LEBRE', 'CANGURU', 'KOALA', 'PANDAS', 'GORILA', 'CHIMPANZÉ', 'ORANGOTANGO', 'MACACO', 'MICO', 'SAGUI', 'TAMANDUÁ', 'PREGUIÇA', 'TATU', 'CAPIVARA', 'ANTA', 'JAVALI', 'PORCO', 'VACA', 'BOI', 'TOURO', 'CABRA', 'OVELHA', 'CARNEIRO', 'BURRO', 'MULA', 'JUMENTO', 'GALINHA', 'GALO'],
  'Frutas': ['ABACAXI', 'MORANGO', 'BANANA', 'LARANJA', 'UVA', 'MELANCIA', 'ABACATE', 'LIMÃO', 'COCO', 'AMEIXA', 'MANGA', 'PÊRA', 'MAÇÃ', 'KIWI', 'FIGO', 'CAJU', 'TANGERINA', 'FRAMBOESA', 'PAPAYA', 'GOIABA', 'MARACUJÁ', 'JABUTICABA', 'PITANGA', 'GRAVIOLA', 'ACEROLA', 'CARAMBOLA', 'SERIGUELA', 'MAMÃO', 'CUPUAÇU', 'BURITI', 'MANGABA', 'CAMU-CAMU', 'AÇAÍ', 'TAMARINDO', 'JENIPAPO', 'MURICI', 'PITAYA', 'ROMÃ', 'NECTARINA', 'DAMASCO', 'AMORA', 'FRUTA-DO-CONDE', 'JACA', 'LICHIA', 'RAMBUTÃ', 'MANGOSTÃO', 'KAKI', 'NÊSPERA', 'CAQUI', 'PÊSSEGO', 'AMEIXA', 'CEREJA', 'MIRABELA', 'MIRTILO', 'CRANBERRY', 'BLACKBERRY', 'BOYSENBERRY', 'BACABA', 'BACURI', 'BIRIBÁ', 'BURITI', 'CACAU', 'CAJÁ', 'CAMBUCÁ', 'CARAMBOLA', 'CIRIGUELA', 'COCO', 'CUPUAÇU', 'DURIÃO', 'EMBAÚBA', 'FEIJOA', 'FRUTA-PÃO', 'GABIROBA', 'GUABIROBA', 'GUARANÁ', 'INGÁ', 'JABUTICABA', 'JAMBO', 'JENIPAPO', 'LARANJA', 'LICHIA', 'MAMÃO', 'MANGA', 'MARACUJÁ', 'MELANCIA', 'MELÃO', 'NECTARINA', 'NÊSPERA', 'PEQUI', 'PÊRA', 'PÊSSEGO', 'PITANGA', 'PITAYA', 'ROMÃ', 'SERIGUELA', 'TANGERINA', 'TOMATE', 'TUCUMÃ', 'UMBU', 'UVA'],
  'Cores': ['ABÓBORA', 'AÇAFRÃO', 'AMARELO', 'ÂMBAR', 'AMEIXA', 'AMÊNDOA', 'AMETISTA', 'ANIL', 'AZUL', 'BEGE', 'BORDÔ', 'BRANCO', 'BRONZE', 'CÁQUI', 'CARAMELO', 'CARMESIM', 'CARMIM', 'CASTANHO', 'CEREJA', 'CHOCOLATE', 'CIANO', 'CINZA', 'CINZENTO', 'COBRE', 'CORAL', 'CREME', 'DAMASCO', 'DOURADO', 'ESCARLATE', 'ESMERALDA', 'FERRUGEM', 'FÚCSIA', 'GELO', 'GRENÁ', 'GRIS', 'HORTELÃ', 'ÍNDIGO', 'JADE', 'JAMBO', 'LARANJA', 'LAVANDA', 'LILÁS', 'LIMÃO', 'LOIRO', 'MAGENTA', 'MALVA', 'MARFIM', 'MARROM', 'MOSTARDA', 'OCRE', 'OLIVA', 'OURO', 'PÊSSEGO', 'PRATA', 'PRETO', 'PÚRPURA', 'ROSA', 'ROXO', 'RUBRO', 'SALMÃO', 'SÉPIA', 'TERRACOTA', 'TIJOLO', 'TURQUESA', 'UVA', 'VERDE', 'VERMELHO', 'VINHO', 'VIOLETA', 'AMARELO-AVERMELHADO', 'AMARELO-CANÁRIO', 'AMARELO-CINZENTO', 'AMARELO-ENXOFRE', 'AMARELO-ESVERDEADO', 'AMARELO-FOSCO', 'AMARELO-GUALDO', 'AMARELO-LIMÃO', 'AMARELO-OCRE', 'AMARELO-OURO', 'AMARELO-PALHA', 'AMARELO-TORRADO', 'AZUL-ARDÓSIA', 'AZUL-CELESTE', 'AZUL-COBALTO', 'AZUL-FERRETE', 'AZUL-MARINHO', 'AZUL-PAVÃO', 'AZUL-PETRÓLEO', 'AZUL-PISCINA', 'AZUL-TURQUESA', 'AZUL-VIOLETA', 'BRANCO-SUJO', 'CASTANHO-AVERMELHADO', 'CINZA-ARDÓSIA', 'CINZENTO-AZULADO', 'CINZENTO-PÉROLA', 'ROSA-BEBÊ', 'ROSA-CHOQUE', 'VERDE-ABACATE', 'VERDE-ÁGUA', 'VERDE-ALFACE', 'VERDE-AMARELO', 'VERDE-AZUL', 'VERDE-BANDEIRA', 'VERDE-BRONZE', 'VERDE-CINZA', 'VERDE-ESMERALDA', 'VERDE-GARRAFA', 'VERDE-MAR', 'VERDE-MILITAR', 'VERDE-MUSGO', 'VERDE-OLIVA', 'VERMELHO-ALARANJADO', 'VERMELHO-CEREJA', 'VERMELHO-PÚRPURA', 'VERMELHO-TOSTADO', 'ALIZARINA', 'AMARELO-BRASILIS', 'AMARELO-CREME', 'AMARELO-CLARO', 'AMARELO-ESCURO', 'AMARELO-ESVERDEADO', 'AMARELO-OURO-CLARO', 'AMARELO-QUEIMADO', 'AZUL-ALICE', 'AZUL-ARDÓSIA-CLARO', 'AZUL-BRASILIS', 'AZUL-BRASILIS-BRILHANTE', 'AZUL-TÓQUIO', 'ÁGUA-MARINHA', 'ÁGUA-MARINHA-MÉDIA', 'AZUL-TURQUESA-BRILHANTE', 'AZUL-BRASILIS-BRILHANTE', 'AZUL-TÓQUIO', 'ÁGUA-MARINHA', 'ÁGUA-MARINHA-MÉDIA', 'AZUL-TURQUESA-BRILHANTE', 'AZUL-BRASILIS-BRILHANTE', 'AZUL-TÓQUIO', 'ÁGUA-MARINHA', 'ÁGUA-MARINHA-MÉDIA', 'AZUL-TURQUESA-BRILHANTE', 'AZUL-BRASILIS-BRILHANTE', 'AZUL-TÓQUIO', 'ÁGUA-MARINHA', 'ÁGUA-MARINHA-MÉDIA', 'AZUL-TURQUESA-BRILHANTE', 'AZUL-BRASILIS-BRILHANTE', 'AZUL-TÓQUIO'],
  'Países': ['AFEGANISTÃO', 'ÁFRICA DO SUL', 'ALBÂNIA', 'ALEMANHA', 'ANDORRA', 'ANGOLA', 'ANTÍGUA E BARBUDA', 'ARÁBIA SAUDITA', 'ARGÉLIA', 'ARGENTINA', 'ARMÊNIA', 'AUSTRÁLIA', 'ÁUSTRIA', 'AZERBAIJÃO', 'BAHAMAS', 'BAHREIN', 'BANGLADESH', 'BARBADOS', 'BÉLGICA', 'BELIZE', 'BENIM', 'BIELORRÚSSIA', 'BOLÍVIA', 'BÓSNIA E HERZEGOVINA', 'BOTSUANA', 'BRASIL', 'BRUNEI', 'BULGÁRIA', 'BURQUINA FASO', 'BURUNDI', 'BUTÃO', 'CABO VERDE', 'CAMARÕES', 'CAMBOJA', 'CANADÁ', 'CATAR', 'CAZAQUISTÃO', 'CHADE', 'CHILE', 'CHINA', 'CINGAPURA', 'COLÔMBIA', 'COMORES', 'CONGO', 'COREIA DO NORTE', 'COREIA DO SUL', 'COSTA DO MARFIM', 'COSTA RICA', 'CROÁCIA', 'CUBA', 'DINAMARCA', 'DJIBUTI', 'DOMINICA', 'EGITO', 'EL SALVADOR', 'EMIRADOS ÁRABES UNIDOS', 'EQUADOR', 'ERITREIA', 'ESCÓCIA', 'ESLOVÁQUIA', 'ESLOVÊNIA', 'ESPANHA', 'ESTADOS UNIDOS', 'ESTÔNIA', 'ESWATINI', 'ETIÓPIA', 'FIJI', 'FILIPINAS', 'FINLÂNDIA', 'FRANÇA', 'GABÃO', 'GÂMBIA', 'GANA', 'GEÓRGIA', 'GRANADA', 'GRÉCIA', 'GUATEMALA', 'GUIANA', 'GUINÉ', 'GUINÉ-BISSAU', 'GUINÉ EQUATORIAL', 'HAITI', 'HOLANDA', 'HONDURAS', 'HUNGRIA', 'IÊMEN', 'ÍNDIA', 'INDONÉSIA', 'IRÃ', 'IRAQUE', 'IRLANDA', 'ISLÂNDIA', 'ISRAEL', 'ITÁLIA', 'JAMAICA', 'JAPÃO', 'JORDÂNIA', 'KIRIBATI', 'KOSOVO', 'KUWAIT', 'LAOS', 'LESOTO', 'LETÔNIA', 'LÍBANO', 'LIBÉRIA', 'LÍBIA', 'LIECHTENSTEIN', 'LITUÂNIA', 'LUXEMBURGO', 'MACEDÔNIA DO NORTE', 'MADAGASCAR', 'MALÁSIA', 'MALAUÍ', 'MALDIVAS', 'MALI', 'MALTA', 'MARROCOS', 'MARSHALL', 'MAURÍCIA', 'MAURITÂNIA', 'MÉXICO', 'MIANMAR', 'MICRONÉSIA', 'MOÇAMBIQUE', 'MOLDÁVIA', 'MÔNACO', 'MONGÓLIA', 'MONTENEGRO', 'NAMÍBIA', 'NAURU', 'NEPAL', 'NICARÁGUA', 'NÍGER', 'NIGÉRIA', 'NORUEGA', 'NOVA ZELÂNDIA', 'OMÃ', 'OSSÉTIA DO SUL', 'PAÍS DE GALES', 'PAÍSES BAIXOS', 'PALAU', 'PALESTINA', 'PANAMÁ', 'PAPUA-NOVA GUINÉ', 'PAQUISTÃO', 'PARAGUAI', 'PERU', 'POLÔNIA', 'PORTUGAL', 'QATAR', 'QUÊNIA', 'QUIRGUISTÃO', 'QUIRIBATI', 'REINO UNIDO', 'REPÚBLICA CENTRO-AFRICANA', 'REPÚBLICA DEMOCRÁTICA DO CONGO', 'REPÚBLICA DOMINICANA', 'REPÚBLICA TCHECA', 'ROMÊNIA', 'RUANDA', 'RÚSSIA', 'SALOMÃO', 'SAMOA', 'SAN MARINO', 'SANTA LÚCIA', 'SÃO CRISTÓVÃO E NÉVIS', 'SÃO TOMÉ E PRÍNCIPE', 'SÃO VICENTE E GRANADINAS', 'SENEGAL', 'SERRA LEOA', 'SÉRVIA', 'SEYCHELLES', 'SÍRIA', 'SOMÁLIA', 'SRI LANKA', 'SUAZILÂNDIA', 'SUDÃO DO SUL', 'SUDÃO', 'SUÉCIA', 'SUÍÇA', 'SURINAME', 'TAILÂNDIA', 'TAIWAN', 'TAJIQUISTÃO', 'TANZÂNIA', 'TIMOR-LESTE', 'TOGO', 'TONGA', 'TRINIDAD E TOBAGO', 'TUNÍSIA', 'TURCOMENISTÃO', 'TURQUIA', 'TUVALU', 'UCRÂNIA', 'UGANDA', 'URUGUAI', 'UZBEQUISTÃO', 'VANUATU', 'VATICANO', 'VENEZUELA', 'VIETNÃ'],
  'Tecnologia': ['ALGORITMO', 'ANDROID', 'ANTIVÍRUS', 'APLICATIVO', 'ARQUIVO', 'AUTOMAÇÃO', 'BACKUP', 'BANDA LARGA', 'BATERIA', 'BIG DATA', 'BITCOIN', 'BLUETOOTH', 'BUG', 'CABO', 'CACHE', 'CLOUD', 'CODIFICAÇÃO', 'COMPUTADOR', 'CONEXÃO', 'COOKIE', 'CPU', 'DADOS', 'DEEP LEARNING', 'DESKTOP', 'DISCO RÍGIDO', 'DOMÍNIO', 'DOWNLOAD', 'DRONE', 'E-COMMERCE', 'E-MAIL', 'ENCRIPTAR', 'FIBRA ÓPTICA', 'FIREWALL', 'FIRMWARE', 'FONTE', 'GIGABYTE', 'HARDWARE', 'HOSPEDAGEM', 'HTML', 'HTTP', 'HTTPS', 'IMPRESSORA', 'INTERNET', 'IP', 'JAVASCRIPT', 'KEYBOARD', 'LAPTOP', 'LED', 'LINUX', 'LOGIN', 'MALWARE', 'MEMÓRIA', 'MICROCHIP', 'MODEM', 'MONITOR', 'NAVEGADOR', 'NFC', 'NODE', 'NOTEBOOK', 'OLED', 'OPEN SOURCE', 'PÁGINA WEB', 'PASSWORD', 'PENDRIVE', 'PIXEL', 'PLACA-MÃE', 'PLUG-IN', 'PORTAL', 'PROCESSADOR', 'PROGRAMA', 'PROXY', 'RAM', 'REDE', 'ROTEADOR', 'SATÉLITE', 'SCRIPT', 'SENSOR', 'SERVER', 'SISTEMA', 'SMARTPHONE', 'SOFTWARE', 'SSD', 'STREAMING', 'SUPORTE', 'TABLET', 'TECNOLOGIA', 'TECLADO', 'TELECOMUNICAÇÃO', 'TELA', 'TERABYTE', 'TOKEN', 'UPLOAD', 'URL', 'USB', 'VÍRUS', 'VPN', 'WEBCAM', 'WEBSITE', 'WIFI', 'XML', 'YOUTUBE', 'ZAP'],
  'Profissões': ['ADVOGADO', 'ARQUITETO', 'ENGENHEIRO', 'MÉDICO', 'PROFESSOR', 'DENTISTA', 'BOMBEIRO', 'POLICIAL', 'COZINHEIRO', 'ENFERMEIRO','JORNALISTA', 'PSICÓLOGO', 'FARMACÊUTICO', 'VETERINÁRIO', 'NUTRICIONISTA', 'PILOTO', 'SOLDADOR', 'ELETRICISTA', 'PADEIRO', 'FOTÓGRAFO','MARCENEIRO', 'MECÂNICO', 'GARÇOM', 'GEÓLOGO', 'ARTISTA', 'ASTRÔNOMO', 'BALCONISTA', 'BIBLIOTECÁRIO', 'CABELEIREIRO', 'CAMINHONEIRO','CARPINTEIRO', 'CIENTISTA', 'CINEASTA', 'COSTUREIRO', 'DECORADOR', 'ECONOMISTA', 'ESTETICISTA', 'FISIOTERAPEUTA', 'FLORISTA', 'JARDINEIRO','LIXEIRO', 'MANICURE', 'MASSAGISTA', 'MERGULHADOR', 'MOTORISTA', 'OURIVES', 'PEDREIRO', 'PESCADOR', 'PROGRAMADOR', 'RADIALISTA','RECEPCIONISTA', 'REDATOR', 'RELOJOEIRO', 'SERRALHEIRO', 'TAXISTA', 'TÉCNICO', 'TRADUTOR', 'VENDEDOR', 'VIGILANTE', 'ZOOTECNISTA','AGRÔNOMO', 'BALCONISTA', 'BANCÁRIO', 'BARBEIRO', 'BIOQUÍMICO', 'CIENTISTA', 'CORRETOR', 'DUBLADOR', 'ELETRICISTA', 'ENÓLOGO','ESTOFADOR', 'ESTUDANTE', 'FAXINEIRO', 'FISCAL', 'FONOAUDIÓLOGO', 'GARÇOM', 'GESSEIRO', 'GRAFITEIRO', 'GUIA', 'HISTORIADOR','JOALHEIRO', 'LOCUTOR', 'MAESTRO', 'MÁGICO', 'MALABARISTA', 'MARCENEIRO', 'MASSAGISTA', 'MONTADOR', 'MOTOBOY', 'OPERADOR','OURIVES', 'PADEIRO', 'PINTOR', 'PIZZAIOLO', 'PORTEIRO', 'PROFESSOR', 'PUBLICITÁRIO', 'QUÍMICO', 'RECEPCIONISTA', 'RESTAURADOR','SALVA-VIDAS', 'SAPATEIRO', 'SEGURANÇA', 'SOCIÓLOGO', 'TATUADOR', 'TELEFONISTA', 'TERAPEUTA', 'TÉCNICO', 'TURISMÓLOGO','UROLOGISTA', 'VAQUEIRO', 'VITICULTOR', 'XILOGRAVURISTA', 'YOUTUBER', 'ZELADOR', 'ZOÓLOGO', 'ECONOMISTA', 'RELOJOEIRO','AÇOUGUEIRO', 'AEROMOÇA', 'AGENTE', 'ALFAIATE', 'AMBULANTE', 'ANTROPÓLOGO', 'APOSENTADO', 'ARQUEÓLOGO', 'ASTRÓLOGO', 'AUXILIAR','BABÁ', 'BIOMÉDICO', 'CANTOR', 'CERIMONIALISTA', 'CHAVEIRO', 'CHEF', 'CIRURGIÃO', 'DANÇARINO', 'DESENHISTA', 'DESPACHANTE','DIRETOR', 'EDUCADOR', 'ENGRAXATE', 'ENCANADOR', 'ESCRITOR', 'ESTILISTA', 'FREELANCER', 'GARIMPEIRO', 'GUARDA', 'GUIA TURÍSTICO','HACKER', 'HERBORISTA','INTÉRPRETE', 'JOGADOR', 'LADRILHADOR', 'LAVADOR', 'LEILOEIRO', 'METEOROLOGISTA', 'OCEANÓGRAFO', 'PALHAÇO','PESCADOR', 'PRODUTOR', 'PSICANALISTA', 'RADIÓLOGO', 'ROTEIRISTA', 'SAPATEIRO', 'SOMMELIER', 'TEÓLOGO', 'VEREADOR', 'YOGI'],
  'Filmes e Séries': ['TITANIC', 'AVATAR', 'A ORIGEM', 'GLADIADOR', 'TUBARÃO', 'ROCKY', 'PSICOSE', 'ALIEN', 'FROZEN', 'GREASE', 'UP', 'MOANA', 'CINDERELA', 'JUMANJI', 'E.T.', 'CREPÚSCULO', 'DEADPOOL', 'AMADEUS', 'GANDHI', 'CASABLANCA', 'SCARFACE', 'DUNKIRK', 'INTERESTELAR', 'DUNA', 'SHREK', 'MINIONS', 'CORINGA', 'COCO', 'VALENTE', 'CARS', 'ZOOTOPIA', 'MONSTROS S.A.', 'PINÓQUIO', 'MULAN', 'RATATOUILLE', 'ALADDIN', 'STAR WARS', 'HARRY POTTER', 'HOMEM DE FERRO', 'THOR', 'VINGADORES', 'AQUAMAN', 'DIVERGENTE', 'MULHER-MARAVILHA', 'PARASITA', 'MAD MAX', 'BLADE RUNNER', '007 - OPERAÇÃO SKYFALL', 'AMNÉSIA', 'O GRANDE TRUQUE', 'LOGAN', 'DJANGO LIVRE', 'SEVEN', 'MATRIX', 'JURASSIC PARK', 'O ILUMINADO', 'O EXTERMINADOR DO FUTURO', 'FORREST GUMP', 'O REI LEÃO', 'TOY STORY', 'OS INCRÍVEIS', 'WALL-E', 'MEU MALVADO FAVORITO', 'MADAGASCAR', 'A ERA DO GELO', 'KUNG FU PANDA', 'HOTEL TRANSILVÂNIA', 'SONIC - O FILME', 'ENCANTO', 'LUCA', 'STRANGER THINGS', 'LA CASA DE PAPEL', 'BREAKING BAD', 'GAME OF THRONES', 'VIKINGS', 'NARCOS', 'THE WITCHER', 'FRIENDS', 'HOW I MET YOUR MOTHER', 'LOST', 'HOUSE OF CARDS', 'LUCIFER', 'THE CROWN', 'O MANDALORIANO', 'WESTWORLD', 'ANNE WITH AN E', 'BLACK MIRROR', 'THE BOYS', 'SUPERNATURAL', 'PEAKY BLINDERS', 'THE WALKING DEAD', 'RICK AND MORTY', 'SOMBRA E OSSOS', 'OZARK', 'CSI: LAS VEGAS', 'DRAGON BALL Z', 'NARUTO', 'CAVALEIROS DO ZODÍACO', 'DEATH NOTE', 'ONE PIECE', 'FULLMETAL ALCHEMIST', 'MY HERO ACADEMIA', 'TOKYO GHOUL', 'ONE PUNCH MAN', 'ATAQUE DOS TITÃS', 'YU YU HAKUSHO', 'HUNTER X HUNTER', 'NANATSU NO TAIZAI', 'NEON GENESIS EVANGELION', 'SAILOR MOON', 'INUYASHA', 'AKIRA', 'BLEACH', 'DEMON SLAYER', 'COWBOY BEBOP', 'SAMURAI X', 'FLCL', 'SPIRITED AWAY', 'PRINCESA MONONOKE'],
  'Desafiador': ['HIPOPÓTAMO', 'ORNITORRINCO', 'QUIXOTESCO', 'SOTURNO', 'ZIGUEZAGUE', 'PSICÓLOGO', 'XILOFONE', 'HORIZONTE', 'PARADOXO', 'ULTIMATO', 'PNEUMOULTRAMICROSCOPICOSSILICOVULCANOCONIOSE', 'MELANCÓLICO', 'HELICÓPTERO', 'TRANSILVÂNIA', 'CALCIMETRICO', 'ANTÍLOPE', 'VERBOSIDADE', 'PRAGMATISMO', 'HIPERBÓREO', 'XANTOFILA'],
  'Esportes': ['FUTEBOL', 'BASQUETE', 'VÔLEI', 'NATAÇÃO', 'TÊNIS', 'GOLFE', 'HANDEBOL', 'RUGBY', 'ATLETISMO', 'SURFE', 'ESGRIMA', 'CICLISMO', 'SKATE', 'HIPISMO', 'REMO', 'ESQUI', 'SNOWBOARD', 'JUDÔ', 'CARATÊ', 'BOXE', 'TAEKWONDO', 'MUAY THAI', 'MMA', 'JIU-JITSU', 'CAPOEIRA', 'CURLING', 'ALPINISMO', 'ESCALADA', 'TRIATLO', 'PENTATLO', 'BMX', 'MOTOCROSS', 'PARAPENTE', 'RALLY', 'FÓRMULA 1', 'AUTOMOBILISMO', 'CRICKET', 'BEISEBOL', 'SOFTBOL', 'LACROSSE','BADMINTON', 'TÊNIS DE MESA', 'BOLICHE', 'BILHAR', 'POLO', 'CANOAGEM', 'KAYAK', 'ARCO E FLECHA', 'TIRO COM ARCO', 'TIRO ESPORTIVO', 'HALTEROFILISMO', 'CROSSFIT', 'FISICULTURISMO', 'GINÁSTICA ARTÍSTICA', 'GINÁSTICA RÍTMICA', 'PENTATLO MODERNO', 'ESCALADA ESPORTIVA', 'CAVALGADA', 'BALONISMO', 'VÔO LIVRE', 'PARAQUEDISMO', 'SKYDIVING', 'POLO AQUÁTICO', 'MERGULHO', 'MERGULHO LIVRE', 'NADO SINCRONIZADO', 'PESCA ESPORTIVA', 'CORRIDA', 'MARATONA', 'MEIA MARATONA', 'ULTRAMARATONA', 'CORRIDA DE RUA', 'CORRIDA DE AVENTURA', 'MARCHA ATLÉTICA', 'CORRIDA DE REVEZAMENTO', 'CORRIDA DE BARCO', 'CORRIDA DE DRONES', 'ESPORTES ELETRÔNICOS', 'VÔLEI DE PRAIA', 'PETECA', 'FUTSAL', 'FUTEBOL AMERICANO', 'BASEBALL', 'FUTEBOL DE SALÃO', 'CURLING', 'ESQUI ALPINO', 'ESQUI NÓRDICO', 'HÓQUEI NO GELO', 'HÓQUEI SOBRE GRAMA', 'PATINAÇÃO ARTÍSTICA', 'PATINAÇÃO DE VELOCIDADE', 'NADO PEITO', 'NADO COSTAS', 'NADO BORBOLETA', 'NADO MEDLEY', 'SAILING', 'VELA', 'WINDSURF', 'KITESURF', 'BODYBOARD', 'BMX', 'ROLLER DERBY', 'ESCALADA INDOOR', 'SLACKLINE', 'CAVALGADA', 'TRILHAS', 'ULTRATRAIL', 'RODEIO', 'TOURADA', 'KARATE', 'JUDÔ', 'SUMÔ', 'CICLOCROSS', 'ESGRIMA OLÍMPICA', 'CURLING'],
  'Música': ['BEYONCÉ', 'ELVIS PRESLEY', 'MADONNA', 'MICHAEL JACKSON', 'PRINCE', 'TAYLOR SWIFT', 'RIHANNA', 'JUSTIN BIEBER', 'SHANIA TWAIN', 'BRUNO MARS', 'LADY GAGA', 'ADELE', 'ED SHEERAN', 'KATY PERRY', 'MARIAH CAREY', 'JENNIFER LOPEZ', 'SHAKIRA', 'THE WEEKND', 'BILLIE EILISH', 'SELENA GOMEZ', 'WHITNEY HOUSTON', 'JANET JACKSON', 'DRAKE', 'DUA LIPA', 'SAM SMITH', 'ARIANA GRANDE', 'JUSTIN TIMBERLAKE', 'POST MALONE', 'HARRY STYLES', 'MEGHAN TRAINOR', 'SIA', 'MAROON 5', 'COLDPLAY', 'U2', 'QUEEN', 'THE BEATLES', 'ROLLING STONES', 'NIRVANA', 'LINKIN PARK', 'GREEN DAY', 'PINK FLOYD', 'PEARL JAM', 'METALLICA', 'GUNS N\' ROSES', 'AC/DC', 'LED ZEPPELIN', 'BON JOVI', 'RED HOT CHILI PEPPERS', 'IMAGINE DRAGONS', 'RADIOHEAD', 'FOO FIGHTERS', 'AEROSMITH', 'KISS', 'IRON MAIDEN', 'BLACK SABBATH', 'OZZY OSBOURNE', 'DAVID BOWIE', 'BOB DYLAN', 'BRUCE SPRINGSTEEN', 'ELTON JOHN', 'PAUL MCCARTNEY', 'JIMI HENDRIX', 'ERIC CLAPTON', 'STEVIE WONDER', 'RAY CHARLES', 'BOB MARLEY', 'ALICIA KEYS', 'BEYONCÉ', 'JAY-Z', 'EMINEM', 'KANYE WEST', 'LIL NAS X', 'LIZZO', 'CARDI B', 'NICKI MINAJ', 'MILEY CYRUS', 'CHARLI XCX', 'SHANIA TWAIN', 'DOLLY PARTON', 'JOHN LEGEND', 'CHRISTINA AGUILERA', 'BRITNEY SPEARS', 'AVRIL LAVIGNE', 'KELLY CLARKSON', 'ENRIQUE IGLESIAS', 'RICKY MARTIN', 'LUIS FONSI', 'MALUMA', 'J BALVIN', 'ANITTA', 'LUDMILLA', 'IZA', 'PABLLO VITTAR', 'GUSTTAVO LIMA', 'JORGE E MATEUS', 'ZÉ NETO E CRISTIANO', 'WESLEY SAFADÃO', 'LUAN SANTANA', 'MARÍLIA MENDONÇA', 'MAIARA E MARAISA', 'SIMONE E SIMARIA', 'ALOK', 'TIESTO', 'DAVID GUETTA', 'CALVIN HARRIS', 'AVICII', 'MARTIN GARRIX', 'STEVE AOKI', 'ZEDD', 'MARSHMELLO', 'DJ SNAKE', 'MAJOR LAZER', 'BLACKPINK', 'BTS', 'EXO', 'TWICE', 'RED VELVET', 'SUPER JUNIOR', 'GIRLS\' GENERATION', 'BIGBANG', 'TXT', 'MONSTA X', 'STRAY KIDS', 'ATEEZ', 'SEVENTEEN', 'NCT', 'GOT7', 'ITZY', 'IVE', 'ENHYPEN', 'AESPA', 'BILLIE EILISH', 'HALSEY', 'TROYE SIVAN'],
  'História': ['ROMA ANTIGA', 'EGITO ANTIGO', 'GRÉCIA ANTIGA', 'IMPÉRIO ROMANO', 'GUILHOTINA', 'REVOLUÇÃO FRANCESA', 'GUERRA CIVIL', 'PRIMEIRA GUERRA MUNDIAL', 'SEGUNDA GUERRA MUNDIAL', 'GUERRA FRIA', 'RÚSSIA', 'CUBA', 'FASCISMO', 'SOCIALISMO', 'CAPITALISMO', 'JULIUS CAESAR', 'CLEÓPATRA', 'ALEXANDRE O GRANDE', 'NAPOLEÃO', 'MAIA', 'ASTÉCAS', 'INCAS', 'COLONIZAÇÃO', 'DESCOBERTA DAS AMÉRICAS', 'CONQUISTADORES', 'REFORMA PROTESTANTE', 'GUERRA DOS TRINTA ANOS', 'ESCRAVIDÃO', 'ABOLIÇÃO', 'REVOLUÇÃO INDUSTRIAL', 'IMPERIALISMO', 'COLONIALISMO', 'RÉPUBLIQUE', 'CAESAR', 'CONGRESSO DE VERSALHES', 'TRATADO DE PAZ', 'JORNALISMO', 'AQUEDUTO', 'GLOBO', 'FERROVIAS', 'INDÚSTRIA', 'URBANIZAÇÃO', 'NAÇÕES UNIDAS', 'UNESCO', 'OTAN', 'PALESTINA', 'GUILHERME O CONQUISTADOR', 'BARBAROSSAS', 'CRUZADAS', 'ESCREVADOS', 'CARTA MAGNA', 'REI ARTUR', 'BÍBLIA', 'BABILÔNIA', 'SÍRIA', 'PALESTINA ANTIGA', 'MAÇONARIA', 'REPUBLICA', 'GUERRAS NAPOLEÔNICAS', 'GOLPE DE ESTADO', 'CONFEDERAÇÃO', 'FEDERAÇÃO', 'PRINCIPADO', 'REPÚBLICA ROMANA', 'IMPERADOR', 'CAIRO', 'MÚSICA MEDIEVAL', 'HOLANDA', 'IMPÉRIO OTOMANO', 'BÁRBAROS', 'SEDE DE ROMA', 'FUNDADORES DOS ESTADOS UNIDOS', 'CONSTITUIÇÃO', 'INDEPENDÊNCIA', 'GUERRAS PÚNICAS', 'GUERRA DOS EMIRADOS', 'CARTA DE PERMISSIONAMENTO', 'CARTAS DE CREDITO', 'OLIMPÍADAS ANTIGAS', 'OLIMPÍADAS MODERNAS', 'GORDIANO', 'NOMADAS', 'HISTÓRIA ECONÔMICA', 'ESCRITA CUNEIFORME', 'ALFABETO', 'TRILHOS FERROVIÁRIOS', 'ESTADO NOVO', 'BALEIAS', 'CONFLITO ISRAELENSE', 'INFANTARIA', 'AERONÁUTICA', 'REVOLUÇÃO IRANIAN', 'GOLFE', 'EXÉRCITO ROMANO', 'IMPÉRIO BRITÂNICO', 'GOLPE MILITAR', 'REINADO', 'REINO DOS FRANCOS', 'GUERRAS MEDIEVAIS', 'DIREITOS HUMANOS', 'PALESTINA', 'CARAVELAS', 'CINQUENTENÁRIO', 'CONFERÊNCIA DE BANDAUNG', 'COMUNISMO', 'PRESIDENCIALISMO', 'JURISPRUDÊNCIA', 'EMANCIPAÇÃO', 'ACORDO DE PAZ', 'IMPERIALISMO', 'COLONIALISMO', 'ESTATUTO', 'PALESTINA', 'SAQUE DE ROMA'],
  'Natureza': ['ECOSSISTEMA', 'BIOMA', 'FLORA', 'FAUNA', 'MONTANHA', 'RÍO', 'MAR', 'LAGO', 'CACHOEIRA', 'BOSQUE','JUNGLA', 'DESERTO', 'SAVANA', 'PANTANAL', 'AMAZÔNIA', 'ATLÂNTICO', 'PACÍFICO', 'ORLA', 'PRAIA','ILHA', 'ARQUIPELAGO', 'VULCÃO', 'GÊISEIRAS', 'GLACIAL', 'GELADO', 'TERMO', 'ROCHA', 'MINERAL','TERRA', 'SOLO', 'AREIA', 'TERRAÇO', 'VALLIS', 'RAVINA', 'MARGEM', 'FLORESTA', 'ARVORE', 'JARDIM','HORTA', 'CAMPO', 'PRADO', 'POMAR', 'VINHEDO', 'MATA', 'ANIMAIS', 'INSETOS', 'PÁSSAROS', 'MAMÍFEROS','REPTÉIS', 'ANFÍBIOS', 'PEIXES', 'VÍRUS', 'BACTÉRIAS', 'FUNGOS', 'ALGAS', 'REDE', 'CICLO', 'FOZ','SERRA', 'PLANÍCIE', 'BAIXADA', 'CLIMA', 'METEOROLOGIA', 'TEMPORAL', 'SECA', 'CHUVA', 'NEVE','GELO', 'CICLONE', 'TORMENTA', 'RAIOS', 'TROVOADA', 'NEBLINA', 'NEVOEIRO', 'AEROSSOL', 'UMIDADE','POLUIÇÃO', 'RECICLAGEM', 'CONSERVAÇÃO', 'DEGRADAÇÃO', 'SUSTENTABILIDADE', 'NATURAL', 'HIDROLOGIA','BIOLOGIA', 'ECOLOGIA', 'CAMPOS', 'FLORESTAÇÃO', 'PLANTAS', 'FRUTOS', 'FLORAÇÃO', 'BIODIVERSIDADE','ESPÉCIES', 'PROTEÇÃO', 'AGRICULTURA', 'PESCA', 'PECUÁRIA', 'PAISAGEM', 'RELEVO', 'ANÁLISE', 'CONSUMO','JARDINAGEM', 'ESTUDO', 'COLETA', 'TRATAMENTO', 'HÁBITAT', 'SISTEMA', 'BIOMASSA', 'COMPOSTAGEM','FÓSSEIS', 'ROCHAS', 'MINERAIS', 'FONTE', 'CASCATA', 'CENÁRIO', 'CORAL', 'CAVERNAS', 'ARROIO','PASTAGEM', 'CIRCUITO', 'GROTAS', 'ELEVADA', 'VEGETAÇÃO', 'SOLAR', 'HIDRELÉTRICA', 'PANTANO','HORIZONTE', 'QUARTZO', 'CRISTAL', 'CHORRO', 'VEGETAL', 'MANGUE', 'CORREDEIRA', 'REPRESA', 'BAIA','CANOA', 'NASCENTE', 'POÇO', 'ABISMO', 'FOZ', 'NAVEGAÇÃO', 'PRAIA', 'COSTA', 'ALDEIA', 'NATURAL','JACARÉ', 'ANANÁS', 'EUCALIPTO', 'BALEIA', 'ROSEIRA', 'IPÊ', 'CIPÓ', 'GIRASSOL', 'AÇAÍ', 'TUCANO'],
  'Literatura': ['ROMANCE', 'CONTOS', 'POESIA', 'HISTÓRIA', 'ENREDO', 'PERSONAGEM', 'AUTOR', 'ESCRITOR', 'LEITOR','FICÇÃO', 'REALISMO', 'NARRATIVA', 'DRAMA', 'TEATRO', 'TRILOGIA', 'EPOPEIA', 'LEGENDAS', 'MITOS', 'FÁBULAS','POEMA', 'SONETO', 'CRÔNICA', 'CARTAS', 'BIOGRAFIA', 'MEMÓRIA', 'AUTOBIOGRAFIA', 'LIVRO', 'CAPÍTULO','PARÁGRAFO', 'JORNAL', 'REVISTA', 'ANTOLÓGIA', 'ANTICIPAÇÃO', 'INTRODUÇÃO', 'CONCLUSÃO', 'RESENHA', 'ANÁLISE','CRÍTICA', 'ARTIGO', 'OPINIÃO', 'JORNALISMO', 'PUBLICAÇÃO', 'EDIÇÃO', 'REDAÇÃO','CARACTERES', 'ESBOÇO', 'RASCUNHO', 'IMPRIMIR', 'EDITAR', 'DICIONÁRIO', 'GRAMÁTICA', 'LINGUAGEM', 'ESTILO','TEMA', 'CONFLITO', 'RESOLUÇÃO', 'ARCO', 'MOTIVAÇÃO', 'DIÁLOGO', 'MONÓLOGO', 'ATOS', 'CENÁRIO', 'PAUTA','ROTEIRO', 'SCRIPT', 'ATIVIDADES', 'TRILHA', 'CENA', 'GÊNERO', 'HISTORIAL', 'CONTRASTE', 'RETRATO', 'ESCRITURA','REALIDADE', 'ALTO', 'FEITIÇO', 'MAGIA', 'FANTASIA', 'MITOLOGIA', 'LITERATURA', 'SUSPENSE', 'HUMOR', 'AVENTURA', 'ÉPOCA', 'HISTÓRICO', 'SOBRENATURAL', 'ROMANTISMO', 'CLÁSSICO', 'MODERNO', 'FOLCLORE', 'EPISTOLAR','ESTUDO', 'NARRADOR', 'ELOGIO', 'TÍTULO', 'CARACTERÍSTICA', 'ANÁLISE', 'FICÇÃO', 'MEMÓRIA', 'SAGA','ENSAIO', 'TEMA', 'AUTOBIOGRAFIA', 'CRÍTICA', 'PÓLO', 'INSPIRAÇÃO', 'METÁFORA', 'FIGURATIVO', 'CONCEITO','SÍNTESE', 'PERSPECTIVA', 'NARRATIVA', 'DRAMATURGIA', 'GÊNERO', 'ESTILO', 'ELENCO', 'ROTEIRISTA', 'REVISAO','JORNALISTA', 'PESSOAL', 'LEITURA', 'CONTO', 'ABORDAGEM', 'PERFIL', 'CENÁRIO', 'PROSA', 'FICÇÃO'],
  'Culinária': ['ALHO', 'CEBOLA', 'TOMATE', 'ARROZ', 'FEIJÃO', 'CARNE', 'FRANGO', 'PEIXE', 'LEITE', 'OVO','QUEIJO', 'MANTEIGA', 'ÓLEO', 'AZEITE', 'SAL', 'AÇÚCAR', 'FARINHA', 'FERMENTO', 'MAIONESE', 'KETCHUP','MOSTARDA', 'VINAGRE', 'SALSA', 'CEVADA', 'PIMENTA', 'ALFACE', 'RUCULA', 'COUVE', 'BRÓCOLIS', 'ESPINAFRE','CENOURA', 'BATATA', 'MORANGO', 'MAÇÃ', 'BANANA', 'LARANJA', 'PERA', 'ABACATE', 'ABOBRINHA', 'BERINJELA','PIMENTÃO', 'ABÓBORA', 'MELANCIA', 'UVA', 'LIMÃO', 'MANGA', 'PESSEGO', 'KIWI', 'CABELINHO', 'ALMEIRÃO','MEL', 'MAPA', 'TORRADA', 'BISCOITO', 'PÃO', 'PIZZA', 'PASTA', 'LASANHA', 'SOPA', 'CALDO','CREME', 'GELÉIA', 'DOCE', 'BROWNIE', 'TORTA', 'PUDIM', 'BOLINHO', 'CUPCAKE', 'CHOCOLATE', 'CAFÉ','CHÁ', 'SUCO', 'COCA-COLA', 'RED BULL', 'GIN', 'VINHO', 'CERVEJA', 'COQUETEL', 'HAMBURGUER', 'HOT DOG','CHURRASCO', 'FEIJOADA', 'RISOTO', 'MOQUECA', 'CALDEIRADA', 'CASSOULET', 'PAELLA', 'SUSHI', 'SASHIMI','TAPIOCA', 'COXINHA', 'ESFIHA', 'BURGER', 'SHAKE', 'SOBREMESA', 'FRITURA', 'ASSADO', 'GRELHADO', 'STEAK','CARNIÇA', 'FEIJOADA', 'PASTEL', 'ALMOÇO', 'JANTAR', 'CAFÉ DA MANHÃ', 'LANCHE', 'APERITIVO', 'ENTRADAS','PRATO PRINCIPAL', 'SAUDADE', 'COSTELA', 'TORRESMO', 'SOBREMESA', 'TEMPEROS', 'CALDO', 'CROSTINI', 'MOLHO','EMBUTIDO', 'ALICATE', 'SILICONE', 'PICANTE', 'FRESCO', 'ORÉGANO', 'MANJERICÃO', 'ALCAPARRA', 'JAMÓN','BACON', 'DADINHO', 'CARAMELIZADO', 'CANELA', 'BAUNILHA', 'MANTEIGA', 'BATATA FRITA', 'POLENTA', 'CROSTAS'],
  'Ciência': ['FÍSICA', 'QUÍMICA', 'BIOLOGIA', 'ASTRONOMIA', 'ECOLOGIA', 'GENÉTICA', 'METALURGIA', 'MATEMÁTICA', 'NEUROCIÊNCIA', 'BOTÂNICA', 'PALEONTOLOGIA', 'FISIOLOGIA', 'METEOROLOGIA', 'ANTROPOLOGIA', 'ZOOLOGIA', 'ASTROFÍSICA', 'CITOLOGIA', 'TEORIAS', 'ESPAÇO', 'FENÔMENOS'],
  'Arquitetura': ['PIRÂMIDE', 'CATEDRAL', 'MUSEU', 'PALÁCIO', 'ARRAIAL', 'FORTALEZA', 'TEMPLO', 'TORRE', 'FAROL', 'ANFITEATRO', 'IGREJA', 'AUDITÓRIO', 'ESTÁDIO', 'MONUMENTO', 'ESCOLA', 'BIBLIOTECA', 'MERCADO', 'BARRACÃO', 'MANSÃO', 'COBERTURA'],
  'Viagens': ['PARIS', 'LONDRES', 'NOVA IORQUE', 'TOKYO', 'ROMA', 'MADRI', 'DUBAI', 'SYDNEY', 'CIDADE DO CABO', 'BARCELONA', 'AMSTERDÃ', 'LOS ANGELES', 'MONTREAL', 'VENEZA', 'ISTAMBUL', 'SANTIAGO', 'BUENOS AIRES'],
  'Festival': ['CARNAVAL', 'FESTIVAL DE CINEMA', 'LOLLAPALOOZA', 'ROCK IN RIO', 'FESTA JUNINA', 'OKTOBERFEST', 'FESTIVAL DE JAZZ', 'FESTIVAL DE MÚSICA', 'FESTIVAL DE DANÇA', 'FESTIVAL DE CERVEJA', 'FESTIVAL DE COMÉDIA', 'FESTIVAL DE LITERATURA', 'FESTIVAL DE ARTE', 'FESTIVAL DE ANIMAÇÃO', 'FESTIVAL DE TEATRO', 'FESTIVAL DE CERVEJA ARTESANAL', 'FESTIVAL DE DANÇA URBANA', 'FESTIVAL DE FOOD TRUCKS'],
  'Super-Heróis e Vilões': ['SUPER-HERÓI', 'VILÃO', 'BATMAN', 'SUPERMAN', 'HOMEM-ARANHA', 'WONDER WOMAN', 'FLASH', 'AQUAMAN', 'MULHER-MARAVILHA', 'CICLOPE','MAGNETO', 'LOKI', 'THOR', 'VIÚVA NEGRA', 'HULK', 'DEADPOOL', 'NICK FURY', 'IRON MAN', 'HAWKEYE', 'DOUTOR ESTRANHO','CAPITÃO AMÉRICA', 'WOLVERINE', 'GAMBIT', 'GROOT', 'ROGUE', 'STORM', 'JUBILEU', 'HOMEM DE FERRO', 'DOOMSDAY', 'JOKER','HOMEM-MORCEGO', 'HOMEM-AREIA', 'ELECTRO', 'RHINO', 'VENOM', 'MAGNETO', 'DOCTOR OCTOPUS', 'HOMEM-ARANHA', 'BANE', 'CHARADA', 'PINGUIM', 'HOMEM-AREIA', 'CAPITÃO FRIO', 'ZODIACO','BLACK PANTHER', 'ICE-MAN', 'ELEKTRA', 'SPIDER-WOMAN', 'SILVER SAMURAI','FANTASMA', 'MORBIUS', 'GHOST RIDER',  'SHOCKER', 'KILLER FROST', 'ALFRED', 'GORDON', 'RORSCHACH', 'CAT-WOMAN', 'CAPITÃO MARVEL', 'MISS MARVEL', 'DARKSEID', 'DEATHBLOW', 'BAT-GIRL', 'GAMORA', 'ROCKET RACCOON', 'MANTIS', 'QUICKSILVER', 'ANT-MAN', 'YONDU', 'SHURI', 'BLACK ADAM', 'BATWOMAN', 'PANTERA NEGRA', 'CAPITÃO MARVEL', 'RAIDER','ABOMINAÇÃO', 'BATGIRL', 'CROSSBONES', 'SHE-HULK', 'DEATHLOCK'],
  'Emoções e Sentimentos': ['FELICIDADE', 'TRISTEZA', 'RAIVA', 'AMOR', 'MEDO', 'ALEGRIA', 'ANGÚSTIA', 'ANSIEDADE', 'DESESPERO', 'CONTENTAMENTO','SORRISO', 'CHORO', 'ALIVIO', 'INSEGURANÇA', 'FRUSTRAÇÃO', 'ENTUSIASMO', 'NOSTALGIA', 'DECEPÇÃO', 'NOJO', 'SURPRESA','CULPA', 'VERGONHA', 'ORGULHO', 'CIÚMES', 'CALMA', 'EXCITAÇÃO', 'SERENIDADE', 'INCOMODADO', 'RESSENTIMENTO', 'CONFUSÃO','ENTREGA', 'CARINHO', 'ODIO', 'CARÁTER', 'HUMILHAÇÃO', 'SAUDADE', 'SOLIDÃO', 'NERVOSISMO', 'TRISTEZA', 'PAVOR','ADMIRAÇÃO', 'AGRADÁVEL', 'DESEJO', 'RESENTIMENTO', 'CONFORTO', 'INQUIETUDE', 'ISOLAMENTO', 'LEVEZA', 'DÚVIDA', 'EUPHORIA','EGOÍSMO', 'DORES', 'APATIA', 'ANIMO', 'PAIXÃO', 'INVEJA', 'SENTIMENTO', 'CARINHOSO', 'AFETO', 'RANCOR', 'AUSÊNCIA','LÁGRIMAS', 'SUSPIRO', 'AGITAÇÃO', 'AFLIÇÃO', 'DESESPERANÇA', 'EGOÍSTICO', 'SIMPATIA', 'DESAMOR', 'ENTUSIASMADO', 'DEZILUSÃO','ALUCINAÇÃO', 'INFLUÊNCIA', 'FELIZ', 'CONTURBADO', 'IMPACTO', 'ESTRESSE', 'DESEJO', 'SOLIDÁRIO', 'CALMANTE', 'CHATEADO','SERIEDADE', 'ESCAPISMO', 'COMPASSIVO', 'ISOLADO', 'BRAVURA', 'RECONHECIMENTO', 'AGRADO', 'OUSADIA', 'PACIÊNCIA', 'DUVIDOSO','SUSTO', 'TRISTEZA', 'ENTREGA', 'VULNERABILIDADE', 'ENTUSIASMO', 'ADMIRADO', 'EXTROVERTIDO', 'HARMONIA', 'DESEJO', 'APROVAÇÃO','MENTALIDADE', 'IMPOTÊNCIA', 'EVASÃO', 'SENSIBILIDADE', 'IRRITAÇÃO', 'SIMPATIA', 'ESTRANHEZA', 'CALOR', 'APOIO', 'ENERGIA','PREOCUPAÇÃO', 'INSEGURANÇA', 'ENTREGA', 'ACOLHIMENTO', 'ALERTA', 'JÚBILO', 'ALEGRIA', 'ACIDENTAL', 'SENSUALIDADE'],
  'Marcas Famosas': ['APPLE', 'SAMSUNG', 'MICROSOFT', 'GOOGLE', 'AMAZON', 'NIKE', 'ADIDAS', 'SONY', 'DELL', 'HP','LG', 'IBM', 'INTEL', 'CISCO', 'ORACLE', 'SIEMENS', 'TESLA', 'FORD', 'CHEVROLET', 'TOYOTA','HONDA', 'BMW', 'MERCEDES', 'AUDI', 'VOLKSWAGEN', 'NISSAN', 'JAGUAR', 'LAND ROVER', 'RENAULT', 'PEUGEOT','KIA', 'HYUNDAI', 'FERRARI', 'LAMBORGHINI', 'PORSHE', 'JEEP', 'CHRYSLER', 'MITSUBISHI', 'SUBARU', 'MAZDA','BURBERRY', 'GUCCI', 'PRADA', 'LOUIS VUITTON', 'CHANEL', 'DIOR', 'FENDI', 'VERSACE', 'HERMÈS', 'YVES SAINT LAURENT','RALPH LAUREN', 'CALVIN KLEIN', 'TOMMY HILFIGER', 'VANS', 'CONVERSE', 'PUMA', 'UNDER ARMOUR', 'NEW BALANCE', 'LEVI\'S','ZARA', 'H&M', 'FOREVER 21', 'GAP', 'NIKE', 'ADIDAS', 'UNDER ARMOUR', 'REEBOK', 'MERCURY', 'BOSS', 'RAY-BAN', 'OAKLEY', 'TAG HEUER', 'ROLEX', 'OMEGA', 'HUGO BOSS', 'LACOSTE', 'CHLOÉ', 'MICHAEL KORS', 'COACH', 'LULULEMON', 'FILA', 'CHAMPION'],
  'Nomes': ['ANA', 'BEATRIZ', 'CARLA', 'DANIELA', 'ELENA', 'FERNANDA', 'GABRIELA', 'HELENA', 'ISABELA', 'JULIA','KARLA', 'LIVIA', 'MARIA', 'NATALIA', 'OLGA', 'PATRICIA', 'QUITERIA', 'RENATA', 'SANDRA', 'TATIANA','URSULA', 'VANESSA', 'WALDIR', 'YASMIN', 'ZILDA', 'ALEX', 'BRUNO', 'CARLOS', 'DANILO', 'EDUARDO','FELIPE', 'GUSTAVO', 'HENRIQUE', 'IVAN', 'JONAS', 'KLEBER', 'LEONARDO', 'MARCOS', 'NANDO', 'OTÁVIO','PAULO', 'QUINTINO', 'RAFAEL', 'SÉRGIO', 'TIAGO', 'URSULO', 'VITOR', 'WILLIAM', 'YURI', 'ZÉ','ALICE', 'BRUNA', 'CLARA', 'DAVID', 'ELIAS', 'FRANCISCO', 'GUILHERME', 'HEITOR', 'IGOR', 'JESSICA','KAREN', 'LUANA', 'MAYARA', 'NICOLAS', 'OLIVIA', 'PEDRO', 'QUIZ', 'RAFAELA', 'SILVIA', 'THAIS','URANIA', 'VALERIA', 'WALTER', 'YAGO', 'ZARA', 'ADRIANO', 'BÁRBARA', 'CAMILA', 'DIEGO', 'EMILIA','FABIOLA', 'GUSTAVA', 'HUGO', 'IVETE', 'JÉSSICA', 'KÁTIA', 'LILIANA', 'MARCELO', 'NATÁLIA', 'OTÁVIA','PRISCILA', 'QUINCY', 'RICK', 'SILVIA', 'THIAGO', 'URIAS', 'VIVIANE', 'WILSON', 'YARA', 'ZÉLIA','ADRIANA', 'BRUNO', 'CAROLINA', 'DANIEL', 'EDSON', 'FERNANDO', 'GABRIEL', 'HELIO', 'ISRAEL', 'JULIANO','KATIA', 'LUCIANA', 'MARIO', 'NANDINHO', 'ORLANDO', 'PATRICK', 'QUEILA', 'RENATO', 'SILVIO', 'TOMÁS','URSI', 'VALENTINA', 'WAGNER', 'YOUNG', 'ZICO', 'ANDREA', 'BÁRBARA', 'CESAR', 'DÉBORA', 'ESTELA','FELICIANO', 'GABRIEL', 'HELOISA', 'JOSÉ', 'KELLEN', 'LUIZ', 'MARGARETH', 'NELSON', 'OLÍVIA', 'PAULINHO'],
  'Astrologia': ['ÁRIES', 'TOURO', 'GÊMEOS', 'CÂNCER', 'LEÃO', 'VIRGEM', 'LIBRA', 'ESCORPIÃO', 'SAGITÁRIO', 'CAPRICÓRNIO','AQUÁRIO', 'PEIXES', 'SOL', 'LUAS', 'ASCENDENTE', 'MERÚRCIO', 'VÊNUS', 'MARTE', 'JÚPITER', 'SATURNO','URANO', 'NETUNO', 'PLUTÃO', 'ZODÍACO', 'CÉU', 'NATAL', 'MAPA', 'QUADRANTE','ECLIPSE', 'ASTROLOGIA', 'COSMO', 'ASTROS', 'INFLUÊNCIA', 'ANÁLISE', 'LUMINAR', 'MEDITAÇÃO', 'RETROGRADO', 'SOMBRA', 'LUZ', 'CARTAS', 'ELEMENTOS', 'ÁGUA', 'FOGO', 'TERRA', 'AR', 'OPOSIÇÃO','CONJUNÇÃO', 'DECANO', 'CASA', 'SIGNO', 'PLANETA', 'ESTRELA', 'SINTONIA', 'CICLO', 'LUNAR', 'ESPÍRITO', 'SOLAR', 'TERRA','NATALIDADE', 'LUNAR', 'PLANETAS', 'LUZ', 'SATURNO', 'REGRESSIVO', 'CARTAS', 'MAPAS', 'SIGNOS', 'DOMÍNIOS', 'HARMONIA', 'ORBITAL', 'TERRESTRE', 'TAROT', 'ZODIACAL', 'ASCENDENTES', 'URANO', 'NETUNO', 'PLUTÃO'],
  'Ações': ['CORRER', 'PULAR', 'ANDAR', 'VOAR', 'NADAR', 'ESCREVER', 'LER', 'FALAR', 'COMER', 'BEBER','DORMIR', 'ESTUDAR', 'TRABALHAR', 'JOGAR', 'DIRIGIR', 'DESENHAR', 'CANTAR', 'DANÇAR', 'COZINHAR', 'LIMPAR','PINTAR', 'OUVIR', 'ESCUTAR', 'ABRIR', 'FECHAR', 'VESTIR', 'DESVESTIR', 'CONVERSAR', 'APRENDER', 'ENSINAR','ENCONTRAR', 'PERDER', 'CUIDAR', 'ENVIAR', 'RECEBER', 'FESTEJAR', 'GAMBAR', 'RIR', 'CHORAR', 'SORRIR','BRINCAR', 'VIAJAR', 'CONHECER', 'VISITAR', 'PESQUISAR', 'COMPRAR', 'VENDER', 'NEGOCIAR', 'PROCURAR', 'PEGAR','LANÇAR', 'ATIRAR', 'EMPURRAR', 'PUXAR', 'ABRAÇAR', 'BEIJAR', 'CUIDAR', 'RELAXAR', 'RELAJAR', 'INICIAR','PAUSAR', 'CONTINUAR', 'DESAFIAR', 'CUPIR', 'ENFRENTAR', 'ANALISAR', 'DECIDIR', 'PERGUNTAR', 'RESPONDER', 'DESEJAR','VISUALIZAR', 'VER', 'SENTIR', 'EXPLODIR', 'ESCALAR', 'EXERCITAR', 'MEDITAR', 'DEMONSTRAR', 'CONSTRUIR', 'DESTRUIR','APERTAR', 'SOLTAR', 'CALCULAR', 'DIVIDIR', 'MULTIPLICAR', 'SOMAR', 'RECONHECER', 'HABILITAR', 'DESABILITAR', 'ORGANIZAR','SUPORTAR', 'ABOLIR', 'MODIFICAR', 'PERSUADIR', 'DEBATER', 'FOTOGRAFAR', 'GRAVAR', 'RETIRAR', 'CONTRAIR', 'MODIFICAR','GASTAR', 'ECONOMIZAR', 'PRATICAR', 'REALIZAR', 'ACREDITAR', 'NEGAR', 'AVALIAR', 'DESAFIAR', 'AMPLIAR', 'REDUZIR','APROVAR', 'DISCORDAR', 'APROPRIAR', 'DEVIDAR', 'COMUNICAR', 'DEFENDER', 'ABRIR', 'ENCERRAR', 'CUMPRIR', 'DECLARAR','AUTORIZAR', 'FECHAR', 'EXECUTAR', 'RECONHECER', 'FESTIVAL'],
  'Objetos': ['CADERNO', 'LÁPIS', 'CANETA', 'MOUSE', 'TECLADO', 'COMPUTADOR', 'CELULAR', 'TV', 'FRIGORÍFICO', 'CADEIRA','MESA', 'SOFÁ', 'LÂMPADA', 'TELHA', 'JANELA', 'PORTA', 'LIVRO', 'RELOJ', 'GARRAFA', 'TAÇA','PRATO', 'GARFO', 'COLHER', 'FACAS', 'POTES', 'PANELA', 'TIGELA', 'MANTEL', 'TAPETE', 'ALMOFADA','ROUPA', 'CALÇA', 'CAMISA', 'SAPATO', 'TENIS', 'CHINELO', 'BONÉ', 'ÓCULOS', 'ANEL', 'BRACELETE','COLAR', 'BRINCO', 'CINTA', 'CINTO', 'CHAVE', 'BOLSA', 'MOCHILA', 'CARTEIRA', 'REDE', 'MANTA','TRAVESSEIRO', 'LENÇOL', 'TOALHA', 'DESENHO', 'ESTANTE', 'LIVRARIA', 'QUADRO', 'FOTOGRAFIA', 'ESPELHO', 'RACK','DECORAR', 'PAREDE', 'CARTAZ', 'RELÓGIO', 'CD', 'DVD', 'BLU-RAY', 'FONES', 'ALTO-FALANTE', 'MICROFONE','TELEVISÃO', 'ESTANTE', 'ARMÁRIO', 'GAVETA', 'CABIDE', 'ROUPA', 'SAIA', 'VESTIDO', 'SHORTS', 'CAMISETA','CUPCAKE', 'PIROCA', 'SANDÁLIA', 'CHAVEIRO', 'RELÓGIO', 'GLOBO', 'BRISA', 'CAPA', 'CANECAS', 'ESFEROGRÁFICA','LIVRO', 'CADERNO', 'MOUSEPAD', 'CANETA', 'LANTERNA', 'FÓSFORO', 'CAIXA', 'BARRA', 'PORTA-RETRATO', 'ENVELOPE','INSTRUMENTO', 'COLCHA', 'ALMOFADA', 'FOTOCÓPIA', 'TELA', 'MÓVEL', 'TROFÉU', 'APARELHO', 'TELA', 'CADEIRA'],
};

@Component({
  selector: 'app-simple-words-board',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './simple-words-board.component.html',
  styleUrls: [ './simple-words-board.component.css', 'boneco-words-board.component.css' ]
})
export class SimpleWordsBoardComponent {

  temaSelecionado: string = '';
  palavraSecreta: string = '';
  letrasErradas: string[] = [];
  letrasCorretas: string[] = [];
  vidasRestantes: number = 10;
  jogoIniciado: boolean = false;
  gameFinished: boolean = false;
  venceu: boolean = false;

  poste: boolean = false;
  trave: boolean = false;
  corda: boolean = false;
  cabeca: boolean = false;
  corpo: boolean = false;
  bracoEsquerdo: boolean = false;
  bracoDireito: boolean = false;
  pernaEsquerda: boolean = false;
  pernaDireita: boolean = false;
  olhos: boolean = false;

  constructor( private router: Router, private route: ActivatedRoute ) {}

  ngOnInit() {
    this.route.queryParams.subscribe(params => {
      const nivel = params['nivel'];  // Aqui você captura o nível da URL
      this.iniciarJogoAleatorio(nivel);
    });
  }

  iniciarJogoAleatorio(nivel: string) {
    this.iniciarJogo(nivel);
  }

  iniciarJogo(nivel: string = 'facil') {
    this.temaSelecionado = this.sortearTema();
    this.palavraSecreta = this.sortearPalavra(this.temaSelecionado, nivel);
    this.iniciarNovoJogo();
  }

  iniciarNovoJogo() {
    this.jogoIniciado = true;
    this.gameFinished = false;
    this.venceu = false;
    this.letrasErradas = [];
    this.letrasCorretas = [];
    this.vidasRestantes = 10;
    this.poste = false;
    this.trave = false;
    this.corda = false;
    this.cabeca = false;
    this.corpo = false;
    this.bracoEsquerdo = false;
    this.bracoDireito = false;
    this.pernaEsquerda = false;
    this.pernaDireita = false;
    this.olhos = false;
  }

  sortearTema(): string {
    const temasDisponiveis = Object.keys(temas);
    return temasDisponiveis[Math.floor(Math.random() * temasDisponiveis.length)];
  }

  sortearPalavra(tema: string, nivel: string): string {
    let palavras = temas[tema];
  
    if (nivel === 'facil') {
      palavras = palavras.filter(palavra => palavra.length <= 5);
    } else if (nivel === 'medio') {
      palavras = palavras.filter(palavra => palavra.length > 5 && palavra.length <= 10);
    } else if (nivel === 'dificil') {
      palavras = palavras.filter(palavra => palavra.length > 10);
    } 
    else if (nivel === 'aleatorio') {
      palavras = temas[tema];
    }
  
    return palavras[Math.floor(Math.random() * palavras.length)];
  }

  verificarLetra(letra: string) {
    letra = letra.toUpperCase();
    this.palavraSecreta = this.removerAcentos(this.palavraSecreta);
    if (this.palavraSecreta.includes(letra)) {
      if (!this.letrasCorretas.includes(letra)) {
        this.letrasCorretas.push(letra);
      }
    } else {
      if (!this.letrasErradas.includes(letra)) {
        this.letrasErradas.push(letra);
        switch (this.letrasErradas.length) {
          case 1:
            this.poste = true;
            break;
          case 2:
            this.trave = true;
            break;
          case 3:
            this.corda = true;
            break;
          case 4:
            this.cabeca = true;
            break;
          case 5:
            this.corpo = true;
            break;
          case 6:
            this.bracoDireito = true;
            break;
          case 7:
            this.bracoEsquerdo = true;
            break;
          case 8:
            this.pernaDireita = true;
            break;
          case 9:
            this.pernaEsquerda = true;
            break;
          case 10:
            this.olhos = true;
            break;
        }
        this.vidasRestantes--;
      }
    }
    this.verificarFimDeJogo();
  }

  verificarFimDeJogo() {
    console.log(this.palavraSecreta)
    if (this.removerEspacosTracos(this.palavraOculta) == this.removerEspacosTracos(this.palavraSecreta)) {
      this.confettiColorido();
      this.confettiColorido();
      this.venceu = true;
      this.gameFinished = true;
    } else if (this.vidasRestantes <= 0) {
      this.gameFinished = true;
    }
  }
  get palavraOculta(): string {
    return this.palavraSecreta.split('').map(letra => this.letrasCorretas.includes(letra) ? letra : '_').join(' ');
  }

  confettiColorido() {
    confetti({
      particleCount: 600,
      spread: 80,
      origin: {
        y: 0.5
      },
      colors: ['#ff00bf', '#8000ff', '#0000ff', '#00ffff', '#00ffbf', '#00ff00', '#ffff00', '#ff8000']
    });
  }
  confettiEscuro() {
    confetti({
      particleCount: 600,
      spread: 80,
      angle: 90,
      origin: {
        y: 0.5
      },
      colors: ['#000000', '#333333', '#666666', '#999999', '#4B4B4B', '#1C1C1C']
    });
  }

  removerEspacosTracos(palavraOculta: string): string {
    palavraOculta = palavraOculta.replace(/\s+/g, '');
    return palavraOculta.replaceAll('_', '');
  }

  removerAcentos(palavra: string): string {
    const mapaAcentos: { [chave: string]: string } = {
      'Á': 'A', 'À': 'A', 'Ã': 'A', 'Â': 'A', 'Ä': 'A',
      'É': 'E', 'È': 'E', 'Ê': 'E', 'Ë': 'E',
      'Í': 'I', 'Ì': 'I', 'Î': 'I', 'Ï': 'I',
      'Ó': 'O', 'Ò': 'O', 'Õ': 'O', 'Ô': 'O', 'Ö': 'O',
      'Ú': 'U', 'Ù': 'U', 'Û': 'U', 'Ü': 'U',
      'Ç': 'C',
      'á': 'a', 'à': 'a', 'ã': 'a', 'â': 'a', 'ä': 'a',
      'é': 'e', 'è': 'e', 'ê': 'e', 'ë': 'e',
      'í': 'i', 'ì': 'i', 'î': 'i', 'ï': 'i',
      'ó': 'o', 'ò': 'o', 'õ': 'o', 'ô': 'o', 'ö': 'o',
      'ú': 'u', 'ù': 'u', 'û': 'u', 'ü': 'u',
      'ç': 'c'
    };
  
    return palavra.split('').map(letra => mapaAcentos[letra] || letra).join('');
  }

  goBack(): void {
    this.router.navigate(['']);
  }
}
